Update cicd.yml

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -50,19 +50,35 @@ jobs:
       - name: Pull Docker Image
         run: docker pull ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}
 
-      - name: Deploy to Kubernetes
-        run: |
-          kubectl apply -f deployment.yaml
-          kubectl rollout status deployment/my-app-deployment
+        deploy:
+    runs-on: ubuntu-latest
+    needs: docker  # This runs after the Docker job is successful
+    steps:
+      - name: SSH into server and pull image
+        uses: appleboy/ssh-action@v0.1.3
+        with:
+          host: ${{ secrets.SERVER_HOST }}
+          username: ${{ secrets.SERVER_USER }}
+          key: ${{ secrets.SERVER_SSH_KEY }}
+          script: |
+            docker pull ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest
+            docker stop nodejs-app || true
+            docker rm nodejs-app || true
+            docker run -d --name nodejs-app -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest
+
+
+    #  - name: Deploy to Kubernetes
+      #  run: |
+      #    kubectl apply -f deployment.yaml
+        #  kubectl rollout status deployment/my-app-deployment
 
 # Notify on failure using Telegram (Optional)
-  notify_failure:
-    runs-on: ubuntu-latest
-    if: failure()
-    steps:
-      - name: Send Telegram Notification on Failure
-        uses: appleboy/telegram-action@0.3.2
-        with:
-          to: ${{ secrets.TELEGRAM_CHAT_ID }}
-          token: ${{ secrets.TELEGRAM_TOKEN }}
-          message: 'CI/CD pipeline failed for commit ${{ github.sha }}'
+#  notify_failure:
+#    runs-on: ubuntu-latest
+  #  #steps:
+    #  - name: Send Telegram Notification on Failure
+     #   uses: appleboy/telegram-action@0.3.2
+      #  with:
+       #   to: ${{ secrets.TELEGRAM_CHAT_ID }}
+         # token: ${{ secrets.TELEGRAM_TOKEN }}
+       #   message: 'CI/CD pipeline failed for commit ${{ github.sha }}'
